revise and refactor session 14: JavaScript Functions
gazaskygeeks/Fundamentals-course pull request #43
Opened 2020-09-07 08:34 UTC by AhmedSafi97

- updated the learning outcomes of the session.

2020-09-11 15:01 UTC, hshahwan submitted a review, later dismissed

2020-09-13 14:47 UTC, MohammedYehia requested changes
Good Job 👍

2020-09-13 14:47 UTC, MohammedYehia commented on coursebook/Week 05/session-14/README.md
> +- 1:00 - 1:55 | [Exercises](./exercises.md)
This one needs to be updated

2020-09-13 14:47 UTC, MohammedYehia commented on coursebook/Week 05/session-14/intro-to-functions.md
> +**Note:** Function names can contain letters, digits, underscores, and dollar signs (same rules as variables).
could you add something about the name -> that it's preferable to be a `verb` rather than a noun

2020-09-13 14:47 UTC, MohammedYehia commented on coursebook/Week 05/session-14/intro-to-functions.md
> +function jsIsFun() {
just a minor thing to be consistent with function names use a verb -> displayJsIsFun, print...etc

2020-09-13 14:47 UTC, MohammedYehia commented on coursebook/Week 05/session-14/intro-to-functions.md
add some wordings here to highlight that "Heisenberg" and "Turing" are the arguments in this case

2020-09-13 14:47 UTC, MohammedYehia commented on coursebook/Week 05/session-14/intro-to-functions.md
> +We can define multiple parameters for a function by comma-separating them. We can pass in up to 255 parameters!
Can you please remove "up to 255 parameters". The [spec](http://www.ecma-international.org/ecma-262/6.0/index.html#sec-list-and-record-specification-type) says `These sequences may be of any length`.

PS: I know that this was originally there from the begining :)

2020-09-13 14:47 UTC, MohammedYehia commented on coursebook/Week 05/session-14/intro-to-functions.md
> +var squareOfTwo = findSquare(2); // Result: 4
Can you please replace all the `var` keyword in this file to `let`. I already introduced let and const on the intro to js so they will be familiar with it

2020-09-13 14:47 UTC, MohammedYehia commented on coursebook/Week 05/session-14/exercises.md
> +**Note:** In mathematics, this is called the factorial of a number an it's denoted by `n!` where `n` is a positive integer.
```suggestion
**Note:** In mathematics, this is called the factorial of a number and it's denoted by `n!` where `n` is a positive integer.
```

2020-09-13 20:34 UTC, AhmedSafi97 commented on coursebook/Week 05/session-14/README.md
> +- 1:00 - 1:55 | [Exercises](./exercises.md)
done :+1:

2020-09-13 20:35 UTC, AhmedSafi97 commented on coursebook/Week 05/session-14/intro-to-functions.md
> +**Note:** Function names can contain letters, digits, underscores, and dollar signs (same rules as variables).
good point  :+1:

2020-09-13 20:35 UTC, AhmedSafi97 commented on coursebook/Week 05/session-14/intro-to-functions.md
> +function jsIsFun() {
done :+1:

2020-09-13 20:35 UTC, AhmedSafi97 commented on coursebook/Week 05/session-14/intro-to-functions.md
done :+1:

2020-09-13 20:37 UTC, AhmedSafi97 commented on coursebook/Week 05/session-14/intro-to-functions.md
> +var squareOfTwo = findSquare(2); // Result: 4
done :+1:

2020-09-13 20:37 UTC, AhmedSafi97 commented on coursebook/Week 05/session-14/exercises.md
> +**Note:** In mathematics, this is called the factorial of a number an it's denoted by `n!` where `n` is a positive integer.
done :+1:

2020-09-13 20:39 UTC, AhmedSafi97 commented on coursebook/Week 05/session-14/intro-to-functions.md
> +We can define multiple parameters for a function by comma-separating them. We can pass in up to 255 parameters!
I found it interesting so I left it :smiley: . 
But, my bad. I should have searched more about it :sweat_smile: .

2020-09-13 20:45 UTC, MohammedYehia commented on coursebook/Week 05/session-14/intro-to-functions.md
> +var squareOfTwo = findSquare(2); // Result: 4
oops sorry just add `const` if it is possible for non-changing variables 
Sorry my bad🙏

2020-09-13 20:52 UTC, AhmedSafi97 commented on coursebook/Week 05/session-14/intro-to-functions.md
> +var squareOfTwo = findSquare(2); // Result: 4
no worries, done :+1:

2020-09-13 20:54 UTC, MohammedYehia approved these changes

2020-09-14 06:23 UTC, hshahwan approved these changes

2020-09-14 06:23 UTC, merged